apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: enterprise-space

type: Opaque

stringData:
  POSTGRES_DB: space_mission_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: injila2005